name: wallafind
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_launcher_name:
    git:
      url: https://github.com/ride4sun/flutter_launcher_name
      ref: "0.9.1"
  flutter_launcher_icons: ^0.13.1
  loading_indicator: ^3.1.1
  lottie: ^2.6.0
  provider: ^6.0.5


#Set name to flutter app:
#flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: "wallafind"

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/
      
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic

flutter_intl:
  enabled: true
